#!/bin/sh -eu

# The directory holding your source code and Cabal file:
SRC_DIR=~/.xmonad/

# The name of the executable produced by cabal.  This comes from the
# executable section of your Cabal file.
EXE_NAME=xmonad-build

# This script will be given a single argument, the path to the
# executable it should produce.
output_file=$1; shift

cd $SRC_DIR

nix-shell --command '
cabal new-configure \
      --enable-optimization \
      --enable-executable-stripping
cabal new-build'

find dist-newstyle -type f -executable -name $EXE_NAME \
     -exec cp '{}' $output_file ';'
